#!/bin/bash

setxkbmap -layout rs -variant latin
sxhkd -c $HOME/.config/bspwm/sxhkd &


bspc monitor -d 1 2 3 4 5 6 7 8 9
xsetroot -cursor_name left_ptr
feh --bg-scale ~/Pictures/Wallpapers/firewatch.jpg

pipewire &
pipewire-pulse
